// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmtj4-dXwSzwsQ6UTyV492GhWGbK4T8LY',
    appId: '1:1033704062031:web:ff42af18204cda9d153e3a',
    messagingSenderId: '1033704062031',
    projectId: 'myportfolioapp-1fa88',
    authDomain: 'myportfolioapp-1fa88.firebaseapp.com',
    storageBucket: 'myportfolioapp-1fa88.firebasestorage.app',
    measurementId: 'G-E8FZK26B6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmnToZIBETGIU4D72TJA0_IvGPEcMU28',
    appId: '1:1033704062031:android:1238f6c0cb9c3b55153e3a',
    messagingSenderId: '1033704062031',
    projectId: 'myportfolioapp-1fa88',
    storageBucket: 'myportfolioapp-1fa88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4IDtU4dPsZdHyOehiJBb79M8fI8Kg3IY',
    appId: '1:1033704062031:ios:c80eef33cd439728153e3a',
    messagingSenderId: '1033704062031',
    projectId: 'myportfolioapp-1fa88',
    storageBucket: 'myportfolioapp-1fa88.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

}